/**
 * Artefactos e versões — Validation Runtime (Fase 4.2).
 */

const VALIDATION_RESULTS_FILENAME = "validation-results.json";
const VALIDATION_RUNTIME_MANIFEST_FILENAME = "validation-runtime-manifest.json";
const VALIDATION_RUNTIME_CACHE_DIRNAME = "validation-runtime-cache";
const VALIDATION_GRAPH_SCHEMA_VERSION = 1;
const VALIDATION_RESULTS_SCHEMA_VERSION = 1;

module.exports = {
  VALIDATION_RESULTS_FILENAME,
  VALIDATION_RUNTIME_MANIFEST_FILENAME,
  VALIDATION_RUNTIME_CACHE_DIRNAME,
  VALIDATION_GRAPH_SCHEMA_VERSION,
  VALIDATION_RESULTS_SCHEMA_VERSION,
};
