import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertTriangle,
  BadgeCheck,
  BookMarked,
  CheckCircle,
  CircleSlash,
  Cpu,
  Eye,
  FileDiff,
  FileText,
  Files,
  Flag,
  GitBranch,
  GitCommitHorizontal,
  GitPullRequest,
  HelpCircle,
  Hourglass,
  Inbox,
  Layers,
  ListTree,
  MessageCircle,
  MessagesSquare,
  OctagonAlert,
  PartyPopper,
  Pause,
  Play,
  PlayCircle,
  RefreshCcw,
  RotateCcw,
  ScrollText,
  Send,
  ShieldCheck,
  SquareStack,
  Target,
  TestTube,
  ThumbsDown,
  ThumbsUp,
  UserRound,
  Wand2,
} from "lucide-react";
import type { ExecutionStepIconName } from "@/lib/runtime/execution/execution-step-catalog";

export const EXECUTION_STEP_ICON_MAP: Record<
  ExecutionStepIconName,
  LucideIcon
> = {
  inbox: Inbox,
  send: Send,
  flag: Flag,
  play: Play,
  activity: Activity,
  "messages-square": MessagesSquare,
  "help-circle": HelpCircle,
  "message-circle": MessageCircle,
  "badge-check": BadgeCheck,
  "git-branch": GitBranch,
  "shield-check": ShieldCheck,
  "list-tree": ListTree,
  layers: Layers,
  "square-stack": SquareStack,
  cpu: Cpu,
  "file-diff": FileDiff,
  files: Files,
  "scroll-text": ScrollText,
  "test-tube": TestTube,
  "check-circle": CheckCircle,
  eye: Eye,
  "thumbs-up": ThumbsUp,
  "thumbs-down": ThumbsDown,
  "wand-2": Wand2,
  "refresh-ccw": RefreshCcw,
  "rotate-ccw": RotateCcw,
  "octagon-alert": OctagonAlert,
  "user-round": UserRound,
  hourglass: Hourglass,
  "alert-triangle": AlertTriangle,
  pause: Pause,
  "play-circle": PlayCircle,
  "circle-slash": CircleSlash,
  "party-popper": PartyPopper,
  target: Target,
  "file-text": FileText,
  "book-marked": BookMarked,
  "git-commit-horizontal": GitCommitHorizontal,
  "git-pull-request": GitPullRequest,
};

export function executionStepIcon(
  name: ExecutionStepIconName,
): LucideIcon {
  return EXECUTION_STEP_ICON_MAP[name] ?? Activity;
}
